### ISSUE TITLE
可以分享一下关于Gait recognition中GREW的数据集么，感谢

### ISSUE THREAD

**Issue by wenzhezhai** [heyihao2018/CV#1]
同学你好，打扰到您。请问可以方便加一下您的联系方式么，关于GREW这个数据集（https://github.com/GREW-Benchmark/）官网网址（https://www.grew-benchmark.org/lander）失效了，请问可以分享一下这个数据集么，万分感谢

**Comment by heyihao2018** [comment]
可以的，我们加个微信吧，18875758768，你就按这个手机号加我就行。我一会用百度网盘发给你啊

**Comment by wenzhezhai** [comment]
万分感谢，但是提示用户不存在，这是我的微信：Sunshine_zwz_，能否麻烦您加一下，感谢

**Comment by heyihao2018** [comment]
好的
